name: Website

on:
  push:
    branches: [main]
  pull_request:
  workflow_dispatch:

concurrency:
  group: website-${{ github.ref }}
  cancel-in-progress: true

jobs:
  website:
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # TODO:
      # run formatter & linter
      # run typechecker
      # run tests

      - name: Build image
        run: docker build --pull -t $REGISTRY_URI/website:${{ github.sha }} .

      # TODO:
      # run trivy
      # trivy image --exit-code 1 --severity HIGH,CRITICAL $REGISTRY_URI/website:${{ github.sha }}

      - name: Tag image
        if: github.event_name == 'push'
        run: |
          docker tag \
            $REGISTRY_URI/website:${{ github.sha }} \
            $REGISTRY_URI/website:latest

      - name: Push image
        if: github.event_name == 'push'
        run: |
          docker push $REGISTRY_URI/website:${{ github.sha }}
          docker push $REGISTRY_URI/website:latest

      - name: Deploy image
        if: github.event_name == 'push'
        run: docker compose pull && docker compose up -d
