name: Website

on:
  push:
    branches: [main]
  pull_request:
  workflow_dispatch:

concurrency:
  group: website-${{ github.ref }}
  cancel-in-progress: true

jobs:
  website:
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 24
          cache: npm

      - name: Install dependencies
        run: npm ci
        env:
          HUSKY: 0

      - name: Check formatting
        run: npm run check-format

      - name: Lint repo
        run: npm run lint

      - name: Typecheck repo
        run: npm run typecheck

      - name: Run tests
        run: npm run test

      - name: Build image
        run: docker build --pull -t $REGISTRY_URI/website:${{ github.sha }} .

      # - name: Scan image
      #   run: scan $REGISTRY_URI/website:${{ github.sha }}

      - name: Tag image
        if: github.event_name == 'push'
        run: |
          docker tag \
            $REGISTRY_URI/website:${{ github.sha }} \
            $REGISTRY_URI/website:latest

      - name: Push image
        if: github.event_name == 'push'
        run: |
          docker push $REGISTRY_URI/website:${{ github.sha }}
          docker push $REGISTRY_URI/website:latest

      - name: Deploy image
        if: github.event_name == 'push'
        run: docker compose pull && docker compose up -d
